"""Tests for the "guest must be enabled" guard.

``config.toml`` is generated by the host module from ``tartarus.guests`` and
only ever lists guests whose ``enable`` is true; disabled guests are absent.
The CLI must therefore refuse to build/start/ssh/stop anything that is not in
that generated set, before it touches nix, the state dir, or SSH.

Run from the repository root::

    .venv/bin/python -m pytest tests/test_guard.py -v
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Make the package importable when run with a bare interpreter (no venv).
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from tartarus import cli  # noqa: E402
from tartarus.config import Config, Guest  # noqa: E402
from tartarus.errors import TartarusError  # noqa: E402


def make_config(*guests: Guest) -> Config:
    """A minimal resolved Config carrying *guests* as the enabled set."""
    return Config(
        user="user",
        home_dir=Path("/home/user"),
        flake_path=Path("/home/user/.config/nixcfg"),
        system="aarch64-linux",
        state_root=Path("/home/user/.local/state/tartarus"),
        ssh_dir=Path("/home/user/.ssh"),
        ssh_ca_dir=Path("/home/user/.local/share/tartarus/ssh"),
        x509_ca_dir=Path("/home/user/.local/share/tartarus/x509"),
        enabled_guests=list(guests),
    )


VAULT = Guest(name="vault", kind="vm", id=3)
BOX = Guest(name="box", kind="container", id=4)

# Every command that names a single guest. Values are argv *after* the program
# name, with the guest placeholder replaced as needed by the tests below.
VM_GUEST_COMMANDS = [
    ["status", "NAME"],
    ["start", "NAME"],
    ["spawn", "NAME"],
    ["stop", "NAME"],
    ["restart", "NAME"],
    ["logs", "NAME"],
    ["ssh", "NAME"],
    ["cid", "NAME"],
    ["proxy", "NAME"],
    ["ip", "NAME"],
    ["proxy-ip", "NAME"],
]
CTN_GUEST_COMMANDS = [
    ["--container", "status", "NAME"],
    ["--container", "start", "NAME"],
    ["--container", "spawn", "NAME"],
    ["--container", "stop", "NAME"],
    ["--container", "restart", "NAME"],
    ["--container", "logs", "NAME"],
    ["--container", "ssh", "NAME"],
]


def with_name(argv: list[str], name: str) -> list[str]:
    return [name if arg == "NAME" else arg for arg in argv]


# --- Config.require_guest -------------------------------------------------


def test_enabled_guest_passes():
    config = make_config(VAULT)
    assert config.require_guest("vault", "vm") is VAULT


def test_absent_guest_raises_actionable_error():
    config = make_config(VAULT)
    with pytest.raises(TartarusError) as exc:
        config.require_guest("ghost", "vm")
    message = str(exc.value)
    assert 'guest "ghost" is not enabled on this host' in message
    assert "tartarus.guests.ghost.enable = true" in message
    assert "rebuild" in message


def test_numbered_instance_of_enabled_template_passes():
    config = make_config(VAULT)
    assert config.require_guest("vault-2", "vm") is VAULT


def test_trs_suffix_is_stripped():
    config = make_config(VAULT)
    assert config.require_guest("vault.trs", "vm") is VAULT


def test_numbered_instance_of_disabled_template_raises():
    config = make_config(VAULT)
    with pytest.raises(TartarusError) as exc:
        config.require_guest("ghost-2", "vm")
    # The actionable option names the base template, not the instance number.
    assert "tartarus.guests.ghost.enable = true" in str(exc.value)


def test_enabled_other_kind_reports_kind_mismatch():
    config = make_config(BOX)
    with pytest.raises(TartarusError) as exc:
        config.require_guest("box", "vm")
    assert 'enabled as kind "container"' in str(exc.value)


def test_kind_none_accepts_any_enabled_kind():
    config = make_config(BOX)
    assert config.require_guest("box") is BOX


# --- CLI wiring: every guest-bearing command is guarded -------------------


@pytest.mark.parametrize("argv", VM_GUEST_COMMANDS + CTN_GUEST_COMMANDS)
def test_disabled_guest_command_fails_before_dispatch(monkeypatch, capsys, argv):
    config = make_config(VAULT, BOX)
    monkeypatch.setattr(cli, "load_config", lambda *a, **k: config)

    def _no_dispatch(*_a, **_k):  # pragma: no cover - must never run
        raise AssertionError("dispatch reached for a disabled guest")

    monkeypatch.setattr(cli.vm, "dispatch", _no_dispatch)
    monkeypatch.setattr(cli.ctn, "dispatch", _no_dispatch)

    with pytest.raises(SystemExit) as exc:
        cli.main(with_name(argv, "ghost"))
    assert exc.value.code == 1
    assert "not enabled on this host" in capsys.readouterr().err


@pytest.mark.parametrize("argv", VM_GUEST_COMMANDS + CTN_GUEST_COMMANDS)
def test_enabled_guest_command_reaches_dispatch(monkeypatch, argv):
    config = make_config(VAULT, BOX)
    monkeypatch.setattr(cli, "load_config", lambda *a, **k: config)
    monkeypatch.setattr(cli.flake, "require_flake", lambda _config: None)

    reached: list[str] = []
    monkeypatch.setattr(cli.vm, "dispatch", lambda _c, a: reached.append(a.command))
    monkeypatch.setattr(cli.ctn, "dispatch", lambda _c, a: reached.append(a.command))

    # `box` is the enabled container, `vault` the enabled VM.
    name = "box" if argv[0] == "--container" else "vault"
    expected = argv[1] if argv[0] == "--container" else argv[0]
    cli.main(with_name(argv, name))
    assert reached == [expected]


def test_all_guests_commands_are_not_guarded(monkeypatch):
    config = make_config(VAULT)
    monkeypatch.setattr(cli, "load_config", lambda *a, **k: config)
    monkeypatch.setattr(cli.flake, "require_flake", lambda _config: None)

    reached: list[str] = []
    monkeypatch.setattr(cli.vm, "dispatch", lambda _c, a: reached.append(a.command))

    cli.main(["list"])
    cli.main(["status"])
    assert reached == ["list", "status"]


def test_container_vm_only_commands_still_rejected(monkeypatch, capsys):
    config = make_config(VAULT)
    monkeypatch.setattr(cli, "load_config", lambda *a, **k: config)
    with pytest.raises(SystemExit) as exc:
        cli.main(["--container", "cid", "vault"])
    assert exc.value.code == 1
    assert "MicroVM-only" in capsys.readouterr().err


def test_help_still_works(monkeypatch, capsys):
    monkeypatch.setattr(cli, "load_config", lambda *a, **k: make_config())
    with pytest.raises(SystemExit) as exc:
        cli.main(["--help"])
    assert exc.value.code == 0
    assert "usage: tartarus" in capsys.readouterr().out
