# Minimal, self-contained guest base shared by every tartarus guest (both
# kinds, both host platforms): state version, the guest user, sshd with a
# CA-signed host key, Nix settings and the macOS case-insensitive-store
# terminfo workaround.
#
# Nothing here depends on nixcfg. Guest *content* (packages, secrets, ...)
# arrives through `tartarusGuest.systemConfig`, composed last by default.nix.
{
  config,
  lib,
  pkgs,
  tartarusGuest,
  mkServiceSystem,
  ...
}: let
  inherit
    (lib)
    mkDefault
    mkIf
    mkMerge
    optional
    optionals
    optionalAttrs
    ;
  g = tartarusGuest;

  # This Mac's Nix store volume is case-insensitive APFS. ncurses' terminfo
  # tree has directories that differ only by case (a top-level "X" bucket and a
  # separate "x" bucket) -- fine on the case-sensitive Linux builder that
  # compiles it, but Nix silently rewrites the colliding one when the finished
  # build is copied back into this case-insensitive store. Every guest shares
  # that same corrupted /nix/store, so ncurses' by-first-letter lookup can no
  # longer find e.g. xterm-256color. Recompile just the terminal types guests
  # actually use into a small tree with no case-colliding names.
  guestTerminfo = pkgs.runCommand "guest-terminfo" {nativeBuildInputs = [pkgs.ncurses];} ''
    mkdir -p $out/share/terminfo
    {
      for term in ansi dumb linux screen screen-256color tmux tmux-256color vt100 xterm xterm-256color xterm-color; do
        infocmp -x "$term"
        echo
      done
    } > combined.src
    tic -x -o $out/share/terminfo combined.src
  '';

  pubKeyFile =
    if g.isVm
    then "${g.hostHome}/.ssh/tartarus.pub"
    else "${g.hostHome}/.ssh/containers.pub";

  # The host key reaches both VMs (over a 9p/virtiofs share) and nspawn
  # containers (bind-mounted at /etc/tartarus/ssh) owned by the host user, not
  # root. sshd refuses a host key it does not own, so stage a root-owned 0600
  # tmpfs copy and point sshd at it. Also overwrite the matching public key
  # beside it, so a copy generated by sshd-keygen for the same path (when the
  # share is not up yet) cannot linger and mismatch the private key.
  # A MicroVM's host key arrives over a 9p/virtiofs share owned by the host
  # user, and sshd refuses a host key it does not own -- stage a root-owned
  # 0600 tmpfs copy for sshd to use. A nspawn container instead reads the key
  # in place at /etc/tartarus/ssh; its container-host VM stages that path
  # root-owned before starting the container (see container-host.nix).
  hostkeyStageScript = pkgs.writeShellScript "microvm-ssh-hostkey-stage" ''
    install -d -m 0700 /run/tartarus
    install -m 0600 /etc/tartarus/ssh/ssh_host_ed25519_key /run/tartarus/ssh_host_ed25519_key
    install -m 0644 /etc/tartarus/ssh/ssh_host_ed25519_key.pub /run/tartarus/ssh_host_ed25519_key.pub
    install -m 0644 /etc/tartarus/ssh/ssh_host_ed25519_key-cert.pub /run/tartarus/ssh_host_ed25519_key-cert.pub
  '';

  hostKeyPath =
    if g.isVm
    then "/run/tartarus/ssh_host_ed25519_key"
    else "/etc/tartarus/ssh/ssh_host_ed25519_key";
in {
  imports =
    [
      # sd-boot/initrd setup that does not apply inside a systemd-nspawn
      # container.
      (mkIf (!g.isVm) {boot.isNspawnContainer = true;})
    ]
    # The scripted initrd is deprecated and removed in NixOS 26.11; the guest
    # must boot the systemd initrd. microvm.nix only defaults that on for
    # qemu/cloud-hypervisor/firecracker/stratovirt, so a vfkit guest (macOS)
    # still gets the scripted one and emits the deprecation warning. Set it
    # explicitly for every VM -- tartarus's own store-overlay/register-nix-
    # closure machinery already assumes a systemd initrd. Normal priority so it
    # overrides microvm's `mkDefault false` without conflicting with its
    # `mkDefault true` on the hypervisors it does cover.
    ++ optional g.isVm {boot.initrd.systemd.enable = true;}
    ++ optional g.isVm (mkServiceSystem {
      name = "microvm-ssh-hostkey-stage";
      description = "Stage MicroVM CA-signed SSH host key with correct permissions";
      command = "${hostkeyStageScript}";
      scope = "system";
      wantedBy = ["sshd.service"];
      # sshd-keygen only skips generating /run/tartarus/ssh_host_ed25519_key
      # if that path is already non-empty when its own condition is checked;
      # with no ordering, systemd may run them concurrently and sshd-keygen
      # can clobber the CA-signed key. Force this service to run last.
      after = ["sshd-keygen.service"];
      extraSystemdUnitConfig.Before = ["sshd.service"];
      extraSystemdServiceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
    });

  config = mkMerge [
    {
      system.stateVersion = mkDefault g.nixVersion;

      environment.variables.TERMINFO_DIRS = ["${guestTerminfo}/share/terminfo"];

      nix = {
        settings.experimental-features = ["nix-command" "flakes"];
        gc = mkIf g.isVm {
          automatic = true;
          dates = "daily";
          options = "--max-freed 500M";
        };
      };

      users.groups.user = {};
      users.users.user =
        {
          createHome = true;
          group = "user";
          description = "${g.name} user";
          home = g.user.home;
          linger = true;
          # macOS guests are forced into a system user (host uid 501 < 1000),
          # whose NixOS-default shell is `pkgs.shadow` -> nologin. Pin an
          # interactive shell so `ssh <guest>` works on Darwin too. Low
          # priority so guest content (systemConfig) can pick e.g. zsh. Only
          # needed for system users: nixpkgs already sets
          # `users.defaultUserShell` for normal users, and defining it here
          # again produces a duplicate `mkDefault` (which trips `nix flake
          # check`, where TARTARUS_HOST_UID is unset so `lowHostUid` is false).
          # A nested container runs as a system user too (it matches the host
          # uid for virtiofs-share ownership; see below), so it needs the pin.
          shell = mkIf (g.isVm || (g.inHostVm or false)) (mkIf g.lowHostUid (mkDefault pkgs.bashInteractive));
          extraGroups = ["wheel"];
          openssh.authorizedKeys.keys =
            optionals (builtins.pathExists pubKeyFile) [(builtins.readFile pubKeyFile)];
        }
        // (
          if g.isVm || (g.inHostVm or false)
          then {
            # See build.nix's hostUid comment: virtiofs has no host-side
            # ownership remapping, so the guest uid must match the invoking
            # host uid. NixOS forbids isNormalUser uid < 1000, hence the
            # isSystemUser escape hatch (macOS's first-user uid 501). A nested
            # container matches the host uid too, so files virtiofs hands to the
            # container-host VM are owned by the same uid after the bind mount.
            isNormalUser = !g.lowHostUid;
            isSystemUser = g.lowHostUid;
            uid = mkIf (g.hostUid != null) g.hostUid;
          }
          else {isNormalUser = true;}
        );

      services.openssh = {
        enable = true;
        settings =
          {
            PermitRootLogin = "no";
            PasswordAuthentication = false;
          }
          // optionalAttrs ((g.services.gpgAgentProxy or false) || (g.services.sudoAuthProxy or false)) {
            # Accept host-forwarded stream-local sockets. GnuPG's socketdir on
            # a systemd guest is $XDG_RUNTIME_DIR/gnupg, and sudo-auth-proxy
            # binds under /run/sudo-auth-proxy; sshd must be allowed to create
            # the forward and to replace a stale socket left by a previous
            # session or a locally auto-launched agent.
            AllowStreamLocalForwarding = "yes";
            StreamLocalBindUnlink = "yes";
          }
          // optionalAttrs (g.services.sudoAuthProxy or false) {
            # The per-session selector and the recursion guard, delivered by
            # the host ssh's `SetEnv` (doc §4.3, §10.4).
            AcceptEnv = ["SUDO_AUTH_PROXY_SOCK" "SUDO_AUTH_PROXY_ACTIVE"];
          };
        hostKeys = [
          {
            path = hostKeyPath;
            type = "ed25519";
          }
        ];
        extraConfig = "HostCertificate ${hostKeyPath}-cert.pub";
      };

      # Guest bind directory for the sudo-auth-proxy SSH RemoteForward (doc
      # §4.3, §9.2; review log S14). The bind is done by this guest's sshd
      # *as the guest login user*, so the directory must be owned by that user
      # and be `0700` -- a root-owned 0755 (or root-owned 0700) directory makes
      # every `RemoteForward` fail, loudly, because the host sets
      # `ExitOnForwardFailure=yes`. Only created for guests that request the
      # client.
      systemd.tmpfiles.rules =
        optional (g.services.sudoAuthProxy or false)
        "d /run/sudo-auth-proxy 0700 ${g.user.name} ${g.user.name} -";

      # `security.sudo.extraConfig` is appended as the *tail* of the generated
      # `/etc/sudoers` (this nixpkgs emits no `@includedir`; verified in
      # nixos/modules/security/sudo.nix, where `configFile` is the concatenation
      # ending with `extraConfig` and is written to `/etc/sudoers`). Deploying
      # here means a later `/etc/sudoers.d` fragment cannot negate these
      # `env_keep` entries. Without them sudo's default `env_reset` strips the
      # selector and the recursion guard before the `pam_exec` helper runs
      # (doc §4.3, §10.4; review logs C1/B2).
      security.sudo.extraConfig = mkIf (g.services.sudoAuthProxy or false) ''
        Defaults env_keep += "SUDO_AUTH_PROXY_SOCK"
        Defaults env_keep += "SUDO_AUTH_PROXY_ACTIVE"
      '';

      # Ad-hoc guests are for interactive/debugging use -- surface service
      # failures on the serial console. home-manager-user.service also has no
      # inherent ordering against nix-daemon and can win the race on a fresh
      # boot.
      systemd.services.home-manager-user = {
        after = ["nix-daemon.socket"] ++ optional g.isVm "register-nix-closure.service";
        wants = ["nix-daemon.socket"] ++ optional g.isVm "register-nix-closure.service";
        serviceConfig.StandardOutput = "journal+console";
      };
      systemd.services.sshd.serviceConfig.StandardOutput = "journal+console";
    }

    # Containers do not mount shares; the host bind-mounts /etc/tartarus/ssh
    # and /etc/tartarus/x509 directly, so pre-create their mount points.
    (mkIf (!g.isVm) {
      systemd.tmpfiles.rules = [
        "d /etc/tartarus/ssh 0755 root root -"
        "d /etc/tartarus/x509 0755 root root -"
      ];
    })
  ];
}
