# Runtime configuration for the tartarus CLI (PLAN.md section 6, Phase 6).
#
# At rebuild time this renders `~/.config/tartarus/config.toml`, the single
# place the CLI learns:
#
#   * the **user's** flake root (never the tartarus repo);
#   * the host-runtime paths (state, ssh, and the two CA roots);
#   * every enabled guest's name/kind/effective id and proxy filtering;
#   * the global proxy transport endpoint (`resolvedListenAddresses`).
#
# It is written through home-manager because that is the mechanism that lands a
# file in the user's home on both NixOS and nix-darwin. `id` is the effective
# (forced or auto-assigned) id from `instances.nix`; the CLI derives CID/IP/MAC
# from it locally (mirroring `lib/ids.nix`) and never runs `nix eval` just to
# locate a guest.
{
  config,
  lib,
  options,
  ...
} @ args: let
  inherit
    (lib)
    attrValues
    concatMapStringsSep
    concatStringsSep
    mapAttrsToList
    mkIf
    mkOption
    optionalString
    replaceStrings
    types
    ;

  # Read from the raw module args (specialArgs); a defaulted formal would be
  # ignored by this nixpkgs and shadow `config`.
  username = args.username or "user";
  hostSystem = args.system or builtins.currentSystem;
  isDarwin = lib.hasSuffix "-darwin" hostSystem;
  homeDir =
    args.homeDir
    or (
      if isDarwin
      then "/Users/${username}"
      else "/home/${username}"
    );

  cfg = config.tartarus;
  instances = config.tartarus.instances;
  hasGuests = instances.vm.enabledNames != [] || instances.container.enabledNames != [];

  # The guest (Linux) system the CLI addresses as `packages.<system>.vm-<name>`;
  # mirrors the auto-detection in `nix/lib/mkGuests.nix`.
  guestSystem =
    if cfg.system != null
    then cfg.system
    else if isDarwin
    then
      (
        if hostSystem == "aarch64-darwin"
        then "aarch64-linux"
        else "x86_64-linux"
      )
    else hostSystem;

  # The Python CA layout is `<root>/ca/...` and `<root>/machines/...`, while
  # `nix/host/ca.nix` names the `ca` subdirectory itself, so take its parent.
  sshRoot = builtins.dirOf config.tartarus.ca.ssh.caDir;
  x509Root = builtins.dirOf config.tartarus.ca.x509.caDir;

  # --- minimal TOML rendering ------------------------------------------------
  # Hand-rendered rather than `pkgs.formats.toml`: the schema is tiny, stable,
  # and must match `src/tartarus/config.py` exactly (including the per-guest
  # inline `proxy` table, which the generic generator does not emit).
  esc = s:
    replaceStrings
    ["\\" "\"" "\n" "\r" "\t"]
    ["\\\\" "\\\"" "\\n" "\\r" "\\t"]
    s;
  tStr = s: "\"${esc s}\"";
  tBool = b:
    if b
    then "true"
    else "false";
  tInt = i: toString i;
  tArr = xs: "[${concatMapStringsSep ", " tStr xs}]";
  tInline = attrs: "{ ${concatStringsSep ", " (mapAttrsToList (k: v: "${k} = ${v}") attrs)} }";

  relayBlock = r: let
    targetPortLine = optionalString (r.targetPort != null) "    target_port = ${tInt r.targetPort}\n";
    hostLine = optionalString (r.host != null) "    host = ${tStr r.host}\n";
  in
    "    [[guests.relays]]\n"
    + "    port = ${tInt r.port}\n"
    + targetPortLine
    + "    protocol = ${tStr r.protocol}\n"
    + hostLine;

  guestBlock = g: ''
    [[guests]]
    name = ${tStr g.name}
    kind = ${tStr g.kind}
    id = ${tInt g.id}
    internet = ${tBool g.internet}
    graphical = ${tBool g.graphical}
    autostart = ${tBool g.autostart}
    shared_folder = ${tBool g.sharedFolder}
    requires = ${tArr g.requires}
    ${optionalString ((g.relays or []) != []) (concatStringsSep "" (map relayBlock g.relays))}proxy = ${tInline {
      enable = tBool g.proxy.enable;
      allow_hosts = tArr g.proxy.allowHosts;
    }}
  '';

  toml = ''
    # Generated by tartarus (nix/host/config.nix). Do not edit.
    user = ${tStr username}
    home = ${tStr homeDir}
    system = ${tStr guestSystem}
    flake = ${tStr cfg.flakePath}
    state_root = ${tStr cfg.stateRoot}
    ssh_dir = ${tStr cfg.sshDir}
    ssh_ca_dir = ${tStr sshRoot}
    x509_ca_dir = ${tStr x509Root}
    log = ${tBool cfg.log}

    [proxy]
    enable = ${tBool config.tartarus.proxy.enable}
    location = ${tStr config.tartarus.proxy.location}
    port = ${tInt config.tartarus.proxy.port}
    listen_addresses = ${tArr config.tartarus.proxy.resolvedListenAddresses}
    log = ${tBool config.tartarus.proxy.log}

    ${concatStringsSep "\n" (map guestBlock (attrValues instances.guests))}
  '';
in {
  options.tartarus = {
    flakePath = mkOption {
      type = types.str;
      default = "${homeDir}/.config/nixcfg";
      description = ''
        Absolute path to the user's own flake root, written to config.toml as
        `flake`. It must never point at the tartarus repo. Defaults to the
        nixcfg checkout path.
      '';
    };
    stateRoot = mkOption {
      type = types.str;
      default = "${homeDir}/.local/state/tartarus";
      description = "Per-guest runtime state root (pid/cid/console log/overlay).";
    };
    sshDir = mkOption {
      type = types.str;
      default = "${homeDir}/.ssh";
      description = "The user's SSH directory (client key, known_hosts).";
    };
    system = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "Guest (Linux) system the CLI builds for; when null it is derived from the host.";
    };
    log = mkOption {
      type = types.bool;
      default = false;
      description = "Default logging toggle written to config.toml.";
    };
  };

  # Only when home-manager is present and guests exist. Without home-manager
  # there is nowhere to land the file; the CLI then falls back to its built-in
  # defaults with an actionable warning.
  config = mkIf (hasGuests && options ? home-manager) {
    home-manager.users.${username}.home.file.".config/tartarus/config.toml".text = toml;
  };
}
