# The tartarus HTTP forward proxy: one Squid instance, no MITM, always an
# allowlist, always HTTPS/443-only via CONNECT (PLAN.md section 3.5).
#
# The same file serves three consumers:
#   * the host module (default `mode`), which installs Squid as a host service
#     when `tartarus.proxy.location = "host"`;
#   * `mode = "squidConfig"`, a pure function used by `nix/guest/proxy.nix` to
#     render the identical config inside a guest-hosted proxy VM;
#   * the read-only `tartarus.proxy.{squidConfig,clients,resolvedListenAddresses}`
#     options, which expose exactly what Phase 6's config.toml needs.
#
# ACLs are keyed by the *source* guest IP, so a single `:3128` serves all
# clients (including a cross-kind container reaching a proxy VM) with the
# client's real source address -- see `nix/host/firewall.nix`'s masquerade
# exception.
{
  inputs ? {},
  mode ? "module",
}: let
  mkSquidConfig = {
    lib,
    listenAddresses,
    port,
    log,
    clients,
  }: let
    inherit
      (lib)
      concatMapStringsSep
      concatStringsSep
      optionalString
      replaceStrings
      ;

    # Squid ACL names are a restricted token set; guest names become `g_<safe>`.
    safe = name: replaceStrings ["." "-" " "] ["_" "_" "_"] name;
    acl = name: "g_${safe name}";

    # An empty `dstdomain` matches nothing, but spelling that out with an
    # intentionally unresolvable domain keeps the directive unambiguous.
    hostPatterns = c:
      if c.allowHosts == []
      then ".invalid"
      else concatStringsSep " " c.allowHosts;

    acls =
      concatMapStringsSep "\n" (c: ''
        acl ${acl c.name} src ${c.ip}/32
        acl ${acl c.name}_hosts dstdomain ${hostPatterns c}
      '')
      clients;

    access =
      concatMapStringsSep "\n" (c: ''
        http_access allow ${acl c.name} CONNECT ${acl c.name}_hosts SSL_ports
        http_access deny ${acl c.name}
      '')
      clients;

    httpPorts = concatMapStringsSep "\n" (a: "http_port ${a}:${toString port}") listenAddresses;

    accessLog =
      if log
      then "access_log stdio:/dev/stderr"
      else "access_log none";
  in ''
    # Generated by tartarus (nix/host/proxy.nix). Do not edit.
    visible_hostname tartarus
    httpd_suppress_version_string on

    acl SSL_ports port 443
    acl CONNECT method CONNECT

    ${httpPorts}

    ${acls}

    ${access}
    http_access deny all

    # No cache, no on-disk state, no directory assumptions. There is deliberately
    # no `never_direct` (there is no cache_peer).
    cache deny all
    cache_log none
    pid_filename none
    logfile_rotate 0
    coredump_dir /tmp

    ${accessLog}
  '';
in
  if mode == "squidConfig"
  then mkSquidConfig
  else
    {
      config,
      lib,
      pkgs,
      ...
    } @ args: let
      inherit
        (lib)
        concatMap
        map
        mkIf
        mkMerge
        mkOption
        types
        unique
        ;

      isDarwin = lib.hasSuffix "-darwin" (args.system or builtins.currentSystem);
      username = args.username or "user";
      ids = import ../lib/ids.nix {inherit lib;};

      instances = config.tartarus.instances;
      cfg = config.tartarus.proxy;

      # Every enabled guest that opted into the proxy, as plain records from
      # `instances.nix`. The Phase 1 assertion guarantees `internet = false` for
      # all of them and that the global proxy is enabled, so no further
      # filtering is needed here.
      rawClients =
        map (g: {
          inherit (g) name kind ip;
          allowHosts = g.proxy.allowHosts;
        })
        instances.proxyClients;

      proxyIsGuest = cfg.enable && cfg.location != "host";

      # Darwin guests cannot reach each other (vfkit/vmnet bridge ports are
      # PRIVATE), so a guest-hosted proxy is reached through the host's socat
      # relay bound to the gateway. Squid therefore always sees the gateway as
      # the client, and the per-guest ACLs collapse into one relay client; the
      # unioned allowlist is intentional because the relay cannot distinguish
      # guests.
      clients =
        if isDarwin && proxyIsGuest
        then [
          {
            name = "relay";
            kind = "vm";
            ip = ids.darwinGateway;
            allowHosts = unique (concatMap (c: c.allowHosts) rawClients);
          }
        ]
        else rawClients;

      clientType = types.submodule {
        options = {
          name = mkOption {type = types.str;};
          kind = mkOption {type = types.enum ["vm" "container"];};
          ip = mkOption {type = types.str;};
          allowHosts = mkOption {
            type = types.listOf types.str;
            default = [];
          };
        };
      };

      # One `http_port` per host bridge that actually has a proxy client; the
      # vmnet gateway on Darwin; never loopback. `null` means "derive".
      resolvedListenAddresses =
        if cfg.listenAddresses != null
        then cfg.listenAddresses
        else if isDarwin
        then [ids.darwinGateway]
        else let
          kinds = unique (map (c: c.kind) clients);
          derived =
            map (
              kind:
                if kind == "vm"
                then ids.vmHostIP
                else ids.ctnHostIP
            )
            kinds;
        in
          if derived == []
          then [ids.vmHostIP]
          else derived;

      squidConfig = mkSquidConfig {
        inherit lib clients;
        inherit (cfg) port log;
        listenAddresses = resolvedListenAddresses;
      };

      configFile = pkgs.writeText "tartarus-squid.conf" squidConfig;

      mkService = inputs.nix-service.lib.mkService {
        inherit lib username isDarwin;
        homeManager = false;
      };
    in {
      options.tartarus.proxy = {
        resolvedListenAddresses = mkOption {
          type = types.listOf types.str;
          internal = true;
          readOnly = true;
          default = resolvedListenAddresses;
          description = "Addresses the proxy binds after applying the `listenAddresses` override and the platform/kind defaults.";
        };
        clients = mkOption {
          type = types.listOf clientType;
          internal = true;
          readOnly = true;
          default = clients;
          description = "Enabled guests routed through the proxy, with their source IP and allowlist.";
        };
        squidConfig = mkOption {
          type = types.str;
          internal = true;
          readOnly = true;
          default = squidConfig;
          description = "The rendered Squid configuration (host- or guest-hosted).";
        };
      };

      config = mkMerge [
        # Host-hosted proxy: Squid itself, in user scope (non-privileged port,
        # no root), matching the `bridge`/`nftables`/`CA`-only system boundary.
        (mkIf (cfg.enable && !proxyIsGuest) (mkService {
          name = "tartarus-proxy";
          description = "tartarus HTTP forward proxy (Squid)";
          command = "${pkgs.squid}/bin/squid -N -f ${configFile}";
          scope = "user";
          after = ["network.target"];
          restart = "on-failure";
          extraSystemdServiceConfig.KillSignal = "SIGTERM";
        }))
      ];
    }
